# 5-39 // 명명 패턴보다 애너테이션을 사용하라

명명패턴 : 메서드에 이름을 특정 이름으로 시작하게 만들어 해당 이름이 들어가면 실행

단점
- 오타가 나면 안 된다
- 올바른 프로그램 요소에서만 사용되리라 보증할 방법이 없다
- 프로그램 요소를 매개변수로 전달할 마땅한 방법이 없다

위 단점 애너테이션(@) 으로 해결

## Junit3
```
  public class Testjunit3 extends TestCase {
      public void testjunit3(){
  	     ...
      }
  }
```
- TestCase 를 상속받는다
- 메소드 이름은 항상 test로 시작


## Junit4
```
  public class Testjunit4  {
      @Test
      public void testjunit4(){
  	    ...
      }
  }
```
Junit 4는 Annotation을 사용하여 테스트함
- 명명패턴 단점이 없다.



## 애너테이션 처리

```
public class RunTests {
    public static void main(String[] args) throws Exception{
        int tests = 0;
        int passed = 0;
        Class<?> testClass = Class.forName(args[0]);
        for (Method m : testClass.getDeclaredMethods()) {
            if (m.isAnnotationPresent(Test.class)) {	//Test 애너테이션이 선언된 메서드만을 호출한다.
                tests++;
                try {
                    m.invoke(null);
                    passed++;
                } catch (InvocationTargetException wrappedExc) {
                    Throwable exc = wrappedExc.getCause();
                    System.out.println(m + " 실패 : " + exc);
                } catch (Exception e) {
                    System.out.println("잘못 사용한 테스트 @Test : " + m);
                }
            }
        }
        System.out.printf("suc :: %d, fail : %d%n", passed, tests - passed);
    }
}
```

위오 같이 @Test 애너테이션이 선언된 메서드만 선별하여 호출함


## 매개변수를 받는 애너테이션 타입
```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ExceptionTest {
    Class<? extends Throwable> value();
}
```
ExceptionTest 애너테이의 매개변수는 Throwable을 확장한 모든 클래스가 될 수 있도록 선언함

## 매개변수가 있는 애너테이션 예시
```
public class Sample2 {
    @ExceptionTest(ArithmeticException.class)
    public static void m1() {
        int i = 1 / 0;
    }

    @ExceptionTest(ArithmeticException.class)
    public static void m2() {
        int[] arr = new int[0];
        arr[1] = 1;     // outOfIndex 예외 발생
    }

    @ExceptionTest(ArithmeticException.class)
    public static void m3() {}
}
```
m1 메서드는 @ExceptionTest에 전달된 ArithmeticException을 던지므로 테스트에 성공
m2 메서드는 다른 예외를 던지므로 테스트에 실패
m3 메서드는 예외를 던지지 않으므로 테스트에 실패

```
public class RunExceptionTests {
    public static void main(String[] args) throws Exception{
        int tests = 0;
        int passed = 0;
        Class<?> testClass = Class.forName("chapter6.Sample2");
        for (Method m : testClass.getDeclaredMethods()) {
            if (m.isAnnotationPresent(ExceptionTest.class)) {	//ExceptionTest 애너테이션을 사용한 메서드 선별
                tests++;
                try {
                    m.invoke(null);
                } catch (InvocationTargetException wrappedExc) {
                    Throwable exc = wrappedExc.getCause();
                    Class<? extends Throwable> excType = m.getAnnotation(ExceptionTest.class).value();	// 애너테이션의 매개변수 타입 확인
                    if (excType.isInstance(exc)) {	// 애너테이션의 매개변수 타입과 같을 경우 통과
                        passed++;
                    }
                } catch (Exception e) {
                    System.out.println("잘못 사용한 테스트 @Test : " + m);
                }
            }
        }
        System.out.printf("suc :: %d, fail : %d%n", passed, tests - passed);
    }

}
```